fixed mark as watched no longer working --> EXCEPTION
addonName = xbmcaddon.Addon().getAddonInfo('name').upper()
RuntimeError: No valid addon id could be obtained. None was passed and the script wasn't executed in a normal xbmc manner.